version: '3.8'
services:
  noisy-art:
    build:
      context: .
    environment:
      - OPENAI_API_KEY
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - ./history:/app/history
    ports:
      - "5000:5000"
